### ISSUE TITLE
<SIMON> Wie ist mit Links im MD (lesbar auf Papier) umzugehen 

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/Prozessmodellierung-BPMN-DMN#31]
Zur besseren Lesbarkeit auf Papier müssen die Links auch ausgeschrieben lesbar sein.  In den anderen Lernpfaden sind das Fußnoten am Ende der Seite.

**Wie ist das mit MD zu realisieren?** 

Über die Fußnoten Funktion oder kommen die Links so automatisch ein

**Comment by simondueckert** [comment]
Was meinst du mit "ausgeschrieben", wenn man Markdown ausdruckt?

Standard ist, dass pandoc bei der Konvertierung von MD->TeX->PDF die Fußnoten mit den Links erzeugt. Da muss man nichts extra machen.

**Comment by rednaxelaesor** [comment]
Genau so implementiert.
