### ISSUE TITLE
<SIMON> Sprachtyp des Repositories

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/Prozessmodellierung-BPMN-DMN#32]
Ich habe das Template aus dem Cogneon Repo benutzt
Das ist "Batch"

Die anderen Repos sind aber HTML. 
Wenn ich das MD aus den anderen Repos lese, ist der Code HTML

**Comment by simondueckert** [comment]
Wo kann man diese Einstellung sehen/machen?

**Comment by rednaxelaesor** [comment]
Nicht relevant
