### ISSUE TITLE
<SIMON> Bildformate & Beschriftungen

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/Prozessmodellierung-BPMN-DMN#33]
Welche Bildformate sind erlaubt / Präferiert
Welche Größern
Welche Ausrichtungen
-> Art der Einbindung MD hat mehrere Möglichkeiten

**Comment by simondueckert** [comment]
Das Quellformat muss immer mit im Repository liegen, hier bevorzugen wir SVG, Bearbeitung z.B. mit Inkscape. Für die Einbindung in den Leitfaden dann Exporte in PNG und 1600 Pixel Breite.

Einbindung im Markdown wie in der Doku von Pandoc beschrieben, siehe Überschrift "Pandoc's Markdown" in https://pandoc.org/MANUAL.html
