### ISSUE TITLE
<SIMON> Notation der Überschriften

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/Prozessmodellierung-BPMN-DMN#34]
In Version 1.5 sind 

- in der Überschriften keine Wochen/Kata Zahlen mehr und
- KATA steht immer am Ende der Überschrift

**Comment by simondueckert** [comment]
Die Katas sind losgelöst von den Wochen zu sehen, da die Wochen nur im Format "Circle" relevant sind. Macht man den Lernpfad z.B. in einem Dojo, Summer Camp, Training etc. stimmen die Wochen nicht.

Das "... (Kata)" haben wir ans Ende gestellt, wie bei den Kontexten in Wikipedia. Zunächst stand es am Anfang, aber das sieht im Inhaltsverzeichnis und in Indices komisch aus.

**Comment by rednaxelaesor** [comment]
Genau so implementiert :-)
