### ISSUE TITLE
<SIMON> In wie weit müssen, sollen die im Core genannten in den Child-Lernpfaden genannt werden?

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/Prozessmodellierung-BPMN-DMN#35]
- Hirotaka Takeuchi und Ikujiro Nonaka für die Einführung des Begriffs Scrum für agile Innovationsmethoden (1986).
- Jeff Sutherland und Ken Schwaber für die Definition eines agilen Projektmanagements im Scrum Guide (2010).
- David Allen für die Methode Getting Things Done (GTD), die den Weg zu stressfreier Produktivität von Wissensarbeiter*innen aufzeigt.
- Andy Grove für die Entwicklung der Methode Objectives & Key Results (OKR) als Weiterentwicklung des Management by Objectives (MbO) von Peter Drucker bei Intel (1980er). John Doer für die Einführung von OKR bei Google und Rick Klau von Google Ventures für seinen Vortrag How Google sets goals: OKRs (2013).
- Glyn Moody (2006) und Bryce Williams (2010) für den Begriff und die Definition von Working Out Loud als "Observable Work + Narrating Your Work". John Stepper für die Gestaltung des 12-wöchigen WOL-Lernprogramms, das in den WOL Circle Guides dokumentiert ist (2015). Katharina Krentz von Bosch für ihre vielen Beiträge, Working Out Loud in Organisationen nutzbar zu machen.
- Johannes Müller und Tobias Müller-Zielke für die Vorträge zu OKRs und GTD auf dem lernOS Rockstars Camp 2019 und Alexander Rose für die Zusammenstellung des GTD Lernpfads.

**Comment by simondueckert** [comment]
Die o.g. Quellen sind nur für den lernOS for You Guide relevant. In anderen Guides spielen sie keine Rolle.

**Comment by rednaxelaesor** [comment]
Aus dem Text entfernt
