### ISSUE TITLE
<SIMON> Englischer Lernpfad?

### ISSUE THREAD

**Issue by rednaxelaesor** [rednaxelaesor/Prozessmodellierung-BPMN-DMN#36]
In wie weit sinnvoll?
Bilder sind auch alle deutsch
Mit welchem Aufwand ist zu rechnen?
Wie schätzen wir den Nutzen // Reichweite ein?

**Comment by simondueckert** [comment]
Englischer Lernpfad ist keine Pflicht für lernOS Guides, Expert Debriefing und Podcasting gibt es aktuell auch nur auf Deutsch. Wenn englisch angestrebt: übersetzen mit Word/Office 365, Nacharbeit ca. 2-3 Stunden zzgl. Erstellung mehrsprachiger Bilder.

**Comment by rednaxelaesor** [comment]
Vorerst nicht geplant
